### ISSUE TITLE
【開発：プラットフォーム編】API仕様の整理

### ISSUE THREAD

**Issue by urashin** [urashin/micro-volunteer-docs#11]
**WebAPIの実装とドキュメント整理**

UIで実装されている機能がWebAPI経由で実行できるようAPIを整備し、ドキュメントを作成する。

- [x] controllerからswaggerを自動生成
- [x] thymeleafのUIからAPIをコールするように修正
- [ ] 入力パラメータのバリデーション
- [ ] 入力パラメータのsanitize
- [ ] API側のエラーハンドリング整理
- [ ] UI側のエラーハンドリング整理
- [ ] UIとAPIのrepositoryを分離

**Comment by urashin** [comment]
以下を[現状](https://github.com/urashin/micro-volunteer-pf/blob/master/src/main/java/org/microvolunteer/platform/controller/Controller.java)に合わせて修正する必要がある。
https://github.com/urashin/micro-volunteer-docs/tree/master/200_SystemDesign/220_Platform/222_VolunteerAPI

**Comment by urashin** [comment]
以下を参考に、swaggerを自動的に生成してみる。
https://qiita.com/rhirabay/items/f7527c91b5defc424b9c
https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api
https://qiita.com/NagaokaKenichi/items/b6d4d55a202e6a93d047
https://qiita.com/ftsan/items/5e2c6eb1f435043b309b

**Comment by urashin** [comment]
実際に試したところ、Build時に以下のエラーが出るようになった。
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-02-27 07:03:20.097 ERROR 87013 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xmlModelPlugin': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [springfox.documentation.schema.XmlModelPlugin] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:289) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1302) ~[spring-beans-5.3.13.jar:5.3.13]
```

[このあたりの問題](https://ky-yk-d.hatenablog.com/entry/2019/01/15/001525)が関係していると見て調査中。

**Comment by urashin** [comment]
- Authorization: Bearer headerに関する　[参考記事](https://qiita.com/uasi/items/cfb60588daa18c2ec6f5)
- RestTemplateでheaderを設定するための　[参考記事](https://b1san-blog.com/post/spring/spring-rest-template/)
- Spring Boot のコントローラーでヘッダー情報を`@RequestHeader`により取得する　[参考記事](https://qiita.com/TEBASAKI/items/267c261db17f178e33eb)
